### ISSUE TITLE
Coswara: Breathing, Cough, and Speech Dataset for COVID-19 analysis

### ISSUE THREAD

**Issue by neerajww** [jim-schwoebel/voice_datasets#11]
The prominent symptoms of COVID-19 include cough and breathing difficulties. The database contain respiratory sounds, namely, cough, breath, and speech of healthy and COVID-19 positive individuals. The sound samples are collected via worldwide crowdsourcing using a website application. The curated dataset is released as open access. As the pandemic is evolving, the data collection and analysis is a work in progress. We believe that insights from analysis of Coswara can be effective in enabling sound based technology solutions for point-of-care diagnosis of respiratory infection, and in the near future this can help to diagnose COVID-19.
Link: https://github.com/iiscleap/Coswara-Data

**Comment by jim-schwoebel** [comment]
Thank you, we will addd this now!
