### ISSUE TITLE
2000 HUB5 English not open source

### ISSUE THREAD

**Issue by free-soellingeraj** [jim-schwoebel/voice_datasets#2]
I reached out to LDC last week trying to get ahold of the conversation datasets and was rejected.  LDC does not host open source datasets.  In other words, they suck.

I asked for:
- 2000 HUB5 English

**Comment by jim-schwoebel** [comment]
Aaron,

Thanks for the comment and chiming im here.

Yeah, that's been my experience with LDC too.

It would be nice if they had a more open culture - but such is the nature of how they operate.

We're looking to open source some new datasets similar to the one your mentioning, so will be sure to take it off this list and perhaps find an alternative.

Cheers,

Jim Schwoebel

CEO, SurveyLex

Interested to try a voice survey? 
Try our demo @ https://www.surveylex.com

Donate your voice to help those suffering from psychiatric and neurological conditions @ https://voiceome.org

**Comment by jim-schwoebel** [comment]
just removed this from the list - thank you
