### ISSUE TITLE
Adding "thorsten" german voice dataset (single speaker)

### ISSUE THREAD

**Issue by thorstenMueller** [jim-schwoebel/voice_datasets#6]
Hi @jim-schwoebel .
Thanks for putting together a huge list of available voice/music datasets 👍 .

If you don't mind you could add my free to use "thorsten" dataset too.
https://github.com/thorstenMueller/deep-learning-german-tts/

* german language
* currently used in several approches for free german TTS
* jspeech-1.1 structure
* 22.668 recorded phrases (wav files)
* more than 23 hours of pure audio
* samplerate 22.050Hz
* mono
* normalized to -24dB
* phrase length (min/avg/max): 2 / 52 / 180 chars
* no silence at beginning/ending
* avg spoken chars per second: 14
* sentences with question mark: 2.780
* sentences with exclamation mark: 1.840

**Comment by jim-schwoebel** [comment]
Sure - thanks for suggesting. I'll add it now
