### ISSUE TITLE
New speech dataset

### ISSUE THREAD

**Issue by gabrielmittag** [jim-schwoebel/voice_datasets#9]
We released a new speech quality dataset that could be added. Thank you for putting this list together!

- [NISQA Speech Quality Corpus](https://github.com/gabrielmittag/NISQA/wiki/NISQA-Corpus) - includes 14k speech samples with simulated (codecs, packet-loss, background noise) and live (mobile phone, Zoom, Skype, WhatsApp) voice call degradation conditions. Each file is labelled with subjective ratings of the overall quality and the quality dimensions Noisiness, Coloration, Discontinuity, and Loudness.

**Comment by jim-schwoebel** [comment]
Awesome will add it now! Thanks Gabriel!
